title: 28th Amendment Coalition
description: Welcome to the coalition page for the 28th amendment

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

domain: a28dev.github.io  
url: https://amendment-28.org
baseurl: / 

include:
    - docs/
    - _layouts/

exclude: 
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
